eval(function(p,a,c,k,e,d){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--){d[e(c)]=k[c]||e(c)}k=[function(e){return d[e]}];e=function(){return'\\w+'};c=1};while(c--){if(k[c]){p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c])}}return p}('$(3(){6($("7").4("M")){$.x(y);$.Q("1F://"+$("7").4("v")+"/0/a."+$("7").4("L")+".F?M=1&B="+$.19.B+"&t="+$.1N(),3(){$.x();a()})}i{a()}3 a(){$(\'#9 g[I="J"]\').G(3(){$("#9 .J g").1S(3(){6($(8).1M(":K")){$(8).l().2(\'[12="\'+$(8).4("11")+\'"]\').15("K")}i{$(8).l().2(\'[12="\'+$(8).4("11")+\'"]\').18("K")}})});$(\'#9 g[I="J"]\').D("G");$(\'.9 1T 1g g[I="H"]\').G(3(){6($(8).P()){$(8).l().18("H-17")}i{$(8).l().15("H-17")}});$("#16").C(3(){6(!$("#9").1n()){1m 1l}$("#9 g:1j").1k();$("#9").E();$("#L").N();$("k,7").Z({14:"0"},0);$.Q("//"+$("7").4("v")+"/,/a."+$("7").4("L")+".F?"+($("7").4("M")?"B="+$.19.B+"&":"")+$("#9").1s(),3(){1q(3(){$("#m,#1r").E();$("#10").4("1v",10).p("1b","1a");$("k,7").Z({14:"0"},0)},1h)})});$.Q("//"+$("7").4("v")+"/,/a.1c.F")}});$(3(){A f=$("#o"),e=f.l(),b=f.4("1e");f.1d({1u:y,v:b,1w:3(a){A c;6(a.O.S>5){c=a.O.1U(0,5)+".."}i{c=a.O}e.2(".1O").1P("C").C(3(){f.D("1Q",a)});e.2(".j").k(c)},1V:3(a){e.2(".X").p("U","0%");e.2(".s-o-z").N();6($(".s-m-w").S){$(".s-m-w").N()}i{$.x(y)}},21:3(d,a){A c=0;6(a.23){c=22.20(V*a.1X/a.1Y);e.2(".j").k(c+"%");e.2(".X").p("U",c+"%")}},1Z:3(d,c){6($(".s-m-w").S){$(".s-m-w").E()}i{$.x()}1B{A h=1x.1y(c);Y(1z(h.1E)){u 0:6(f.4("1L")=="y"){e.2("g").P(h.j.T);$("#16").D("C")}i{e.2("g").P(h.j.T);e.2(".1f").p("1H-1G","v(//1I.1J.1K/a/"+h.j.T+")")}n;13:$.1A(h)}}1D(a){$.1C()}e.2(".X").p("U","V%");e.2(".s-o-z").W(R)},1W:3(a){e.2(".j").k("上传失败！");e.2(".s-o-z").W(R)},1R:3(a,c){e.2(".j").k("上传失败！");Y(a[0]){u V:$.r({q:"文件类型错误，只支持上传 "+a[1]+" 格式的图片文件！"});n;u 1i:$.r({q:"文件大小超出限制，最大可上传尺寸为 "+a[1]+" 1p！"});n;u 1o:$.r({q:"超出最大上传数量 "+a[1]+" 的限制！"});n;u 1t:$.r({q:"请不要上传空文件！"});n;13:$.r({q:"文件上传出错了，请稍后再试吧！~"})}e.2(".s-o-z").W(R)}})});',62,128,'||find|function|attr||if|body|this|form|||||||input||else|data|html|parent|loading|break|upload|css|text|myAlert|||case|url|ah|myLoading|true|progress|var|code|tap|trigger|hide|js|change|date|type|radio|checked|create|auth|show|name|val|loadScript|500|length|file|width|100|fadeOut|bar|switch|animate|result|id|for|default|scrollTop|addClass|doCreate|select|removeClass|POST|block|display|_a|myUpload|at|preview|li|1200|101|focus|blur|false|return|formValid|102|KB|setTimeout|loadingTips|serialize|103|one|src|uploadQueue|JSON|parse|parseInt|showError|try|showDataError|catch|rt|http|image|background|ss|tvurl|cn|submitAuto|is|now|cancel|off|delete|uploadError|each|ul|substr|uploadStart|uploadDelete|loaded|total|uploadComplete|ceil|uploadProgress|Math|lengthComputable'.split('|'),0,{}));

var listArr_1 = {
'rich':'<a href="./rich.html"><img src="https://ww1.sinaimg.cn/large/005BYqpgly1fzf87fiawij30dw08cwfi.jpg"><span><b>测测新年你靠什么脱贫</b><b>103万人在玩</b></span><i></i></a>',
'year52':'<a href="./year52.html"><img src="https://ww1.sinaimg.cn/large/005BYqpggy1fzhln3jxipj30dw08mdgu.jpg"><span><b>测测你的2019新年大事件</b><b>84万人在玩</b></span><i></i></a>',
'year12':'<a href="./year12.html"><img src="https://ww1.sinaimg.cn/large/005BYqpggy1fyk6z3hrn3j308w04qgml.jpg"><span><b>测测2019我的猪年运势</b><b>52万人在玩</b></span><i></i></a>',
};
var listArr_2 = {
'year5':'<a href="./year5.html"><img src="https://ww1.sinaimg.cn/large/005BYqpggy1fyghxobyqrj30u00fuwfi.jpg"><span><b>测测2019会发生的5件事</b><b>79万人在玩</b></span><i></i></a>',
'yearword':'<a href="./yearword.html"><img src="https://ww1.sinaimg.cn/large/005BYqpggy1fymbv0doj1j30dw0b43yr.jpg"><span><b>测测哪个字能总结你的2018</b><b>57万人在玩</b></span><i></i></a>',
'meal':'<a href="./meal.html"><img src="https://ww1.sinaimg.cn/large/005BYqpggy1fzgo7tdmw3j30dw0b4tay.jpg"><span><b>测测2019你会靠什么吃饭</b><b>32万人在玩</b></span><i></i></a>',
'10yshenjia':'<a href="./10yshenjia.html"><img src="https://ww1.sinaimg.cn/large/005BYqpggy1fyueimuuavj30dw0b43yq.jpg"><span><b>测测你十年后的身家</b><b>33万人在玩</b></span><i></i></a>',
'renshengchengji':'<a href="./renshengchengji.html"><img src="https://ww1.sinaimg.cn/large/005BYqpgly1fyvslyx8qyj30dw0b4gm4.jpg"><span><b>领取你的人生成绩单</b><b>63万人在玩</b></span><i></i></a>',
'jiuliangchengji':'<a href="./jiuliangchengji.html"><img src="https://ww1.sinaimg.cn/large/005BYqpggy1fzgko5e8xej30dw0b4ad6.jpg"><span><b>领取你的酒量成绩单</b><b>21万人在玩</b></span><i></i></a>',
};

eval(function(p,a,c,k,e,d){e=function(c){return c.toString(36)};if(!''.replace(/^/,String)){while(c--){d[c.toString(a)]=k[c]||c.toString(a)}k=[function(e){return d[e]}];e=function(){return'\\w+'};c=1};while(c--){if(k[c]){p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c])}}return p}('3 2="<7>大家都在玩 ⬇</7>";a(3 i b 8){4(i!=$("6").9("c")){2+=8[i]}}3 1=h.g(d);1=1.e(f(){l n.m()-0.5});a(3 i b 1){4(1[i]!=$("6").9("c")){2+=d[1[i]]}}o.p("k").j=2;',26,26,'|listKey_2|listStr|var|if||body|h4|listArr_1|attr|for|in|create|listArr_2|sort|function|keys|Object||innerHTML|more|return|random|Math|document|getElementById'.split('|'),0,{}))